### ISSUE TITLE
如果是本地搭建，domain这个参数可以是127.0.0.1吗？

### ISSUE THREAD

**Issue by ysben** [MagicalMadoka/openai-signup-tool#1]

**Comment by MagicalMadoka** [comment]
不行，必须要有域名。
其实是必须要有邮箱，域名的作用时生成邮箱。

**Comment by ysben** [comment]
生成的邮箱是随机的吗？比如我设置了domain为：example.com，那么注册成功后的邮箱是不是这样：
aaaa@example.com
bbb@example.com
ccc@example.com

**Comment by MagicalMadoka** [comment]
是的

**Comment by ysben** [comment]
可以指定生成的邮箱吗？比如我用随机邮箱生成然后去注册

**Comment by MagicalMadoka** [comment]
现在不行，如果要改的话应该也很简单，可以看看有没有人提pr
