### ISSUE TITLE
找不到注册账号以及sess

### ISSUE THREAD

**Issue by Happy-clo** [MagicalMadoka/openai-signup-tool#12]
![image](https://github.com/MagicalMadoka/openai-signup-tool/assets/92633092/db3ed526-6a17-4fb4-9c9f-25ed69a25653)
![image](https://github.com/MagicalMadoka/openai-signup-tool/assets/92633092/b4577d74-f9ab-48f7-9a3a-8ba127332fa1)
[openai-signup-tool-20240105224155.log](https://github.com/MagicalMadoka/openai-signup-tool/files/13843289/openai-signup-tool-20240105224155.log)

如图 运行完无任何文件 且docker日志中未发现报错

**Comment by Happy-clo** [comment]
镜像为最新

**Comment by Happy-clo** [comment]
@MagicalMadoka https://github.com/MagicalMadoka/openai-signup-tool/files/13843289/openai-signup-tool-20240105224155.log

**Comment by Happy-clo** [comment]
emm 好像注册未成功

**Comment by Happy-clo** [comment]
[openai-signup-tool-20240106174052.log](https://github.com/MagicalMadoka/openai-signup-tool/files/13848996/openai-signup-tool-20240106174052.log)

**Comment by Happy-clo** [comment]
[openai-signup-tool-20240106174421.log](https://github.com/MagicalMadoka/openai-signup-tool/files/13849008/openai-signup-tool-20240106174421.log)

**Comment by MagicalMadoka** [comment]
Too many signups from the same IP。
