### ISSUE TITLE
proxy报错的问题

### ISSUE THREAD

**Issue by duansix** [MagicalMadoka/openai-signup-tool#13]
测试了几家代理平台
生成的都是这种格式：代理用户名:代理密码@代理服务器:端口（注意不带http）
于是我将这种格式添加到config.json中 报错如下（加了http:// 也不行）：
![20240106091121](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/c9dc1c8f-3ae8-47de-92a0-5dfbe0c24172)
[log.txt](https://github.com/MagicalMadoka/openai-signup-tool/files/13847831/log.txt)

**Comment by MagicalMadoka** [comment]
你用的代理直接请求openai测试一下

**Comment by recbbad** [comment]
@duansix 请问你最后怎么解决的呀。我也是这个问题，带账号密码的，直接代理用requests请求ipinfo.io确实能代理，但是浏览器里没代理成功

**Comment by weikecloud** [comment]
@recbbad @duansix 你们的问题都解决了吗?
