### ISSUE TITLE
开了代理池和yes验证 但好像验证一直过不了

### ISSUE THREAD

**Issue by duansix** [MagicalMadoka/openai-signup-tool#17]
查看代理池和yes 一直在正常消耗扣点数 下面是docker日志 敏感信息已替换
[c2dca5da41bd94f9031b837cbb7749e4398034772fd01603199482733e4da069-json.log](https://github.com/MagicalMadoka/openai-signup-tool/files/13867702/c2dca5da41bd94f9031b837cbb7749e4398034772fd01603199482733e4da069-json.log)

**Comment by MagicalMadoka** [comment]
这些日志显示的是cloudflare还没过。不会消耗yes的。还没到那一步。

我不太确定你是贴错了日志，还是怎么回事。如果没贴错，建议建议你重置一下yes的key，你可能泄漏了

**Comment by duansix** [comment]
日志没有贴错 重新核实 确实yes没有消耗 
这个cf没有过 是因为IP质量的问题吗？
![企业微信截图_20240109103009](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/b0f8a8db-719a-4e18-a27d-e7a34194c383)

**Comment by MagicalMadoka** [comment]
嗯，你可以用你的ip代理自己在浏览器上看一下强度如何。
同时建议先更换掉yes的key。

**Comment by suger404** [comment]
![image](https://github.com/MagicalMadoka/openai-signup-tool/assets/101552636/d25cfc86-f754-41f7-b117-08ab33cc0c63)
可能是域名问题导致的，我两个域名刚刚是被禁用，无法测试，如果你可以的话麻烦说一下  @duansix

**Comment by duansix** [comment]
已经排除域名的问题 就是Cloudflare的验证码过不了导致的 这个有什么办法吗
![QQ截图20240112131741](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/bfda84af-bd3f-4519-abf6-260c12312729)

**Comment by chawaa** [comment]
同样的问题，能解嘛？花钱买住宅ip也不行。
