### ISSUE TITLE
（建议）适配Pandora，可以不需要代理池

### ISSUE THREAD

**Issue by KunBuFenZi** [MagicalMadoka/openai-signup-tool#18]
（建议）适配Pandora，可以不需要代理池
下面是项目地址：https://github.com/pandora-next/deploy

**Comment by MagicalMadoka** [comment]
有一些原因不太适合适配
1. 虽然他现在没限制，不代表以后他不限制。
2. 他的注册没有露出来sess，还要额外登录打码。

**Comment by KunBuFenZi** [comment]
> 有一些原因不太适合适配
> 
> 1. 虽然他现在没限制，不代表以后他不限制。
> 2. 他的注册没有露出来sess，还要额外登录打码。

果然 pandora开始限制了

**Comment by MagicalMadoka** [comment]
pandora将于近期停服，此问题终结
