### ISSUE TITLE
遇到CF的时候可以加上yescaptcha的CF认证吗？

### ISSUE THREAD

**Issue by weikecloud** [MagicalMadoka/openai-signup-tool#19]
文档如下：https://yescaptcha.atlassian.net/wiki/spaces/YESCAPTCHA/pages/86409217/CloudFlareTask+CloudFlare5

**Comment by MagicalMadoka** [comment]
嗯，在写纯协议版本的了，不走浏览器。可以期待一下

**Comment by weikecloud** [comment]
大佬什么时候可以更新，都在等着你的新版呢

**Comment by MagicalMadoka** [comment]
https://github.com/MagicalMadoka/openai-signup-bot

**Comment by weikecloud** [comment]
哇，已经更新好了？
