### ISSUE TITLE
yescaptcha似乎并不起作用？

### ISSUE THREAD

**Issue by duansix** [MagicalMadoka/openai-signup-tool#3]
![20240103114050](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/95269950-30e6-490c-9c17-dc4e5c7ea733)
![20240103114050](https://img.duan.ee/i/2024/01/03/6594d8335d553.png)
![20240103114050](https://img.duan.ee/i/2024/01/03/6594d879c2d2f.png
)

**Comment by MagicalMadoka** [comment]
你图没传上来

**Comment by MagicalMadoka** [comment]
哦。这还没到yes那里。这是cf还没过。

从你的日志来看应该是邮件验证的哪里出现的。正常的ip 一分钟之内肯定可以过的。这个是5分钟都没过。和ip的质量有关。

我刚试了一下，我的ip随便过。高风控的ip过cf确实会麻烦点。

**Comment by duansix** [comment]
proxy支持socks5吗

**Comment by MagicalMadoka** [comment]
支持
