### ISSUE TITLE
一直卡在wait for email verification

### ISSUE THREAD

**Issue by GtxFury** [MagicalMadoka/openai-signup-tool#4]
用的是gmail的imap 邮箱里能正常看到openai发来的验证码，请问有什么解决思路吗

**Comment by MagicalMadoka** [comment]
你先看邮箱里面的邮件状态是已读还是未读。

如果是已读，证明邮件服务没啥问题，最近openai又加了风控，需要过cloudflare。这个和你ip的干净程度有关，越干净过起来越容易，但一般而言最差一分钟也能过了。你尝试换个ip看看

如果未读，应该是邮件服务配置的有问题。
