### ISSUE TITLE
data/account.txt 无权限

### ISSUE THREAD

**Issue by duansix** [MagicalMadoka/openai-signup-tool#5]
PermissionError: [Errno 13] Permission denied: 'data/account.txt'
![20240103163449](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/0a18b8db-9871-488b-bbe7-3ce81bd4efe0)
![20240103163551](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/568c83e3-d7a2-4f20-89ac-594eedaf2d76)

如图所示给了777权限 还是提示没有权限（这两个文件是我手动创建的）

**Comment by MagicalMadoka** [comment]
删掉让他自己建。

star点一下，不然机器人可能会自动关你提的issue
