### ISSUE TITLE
配置了代理池 还是提示ip频繁

### ISSUE THREAD

**Issue by duansix** [MagicalMadoka/openai-signup-tool#9]

**Comment by MagicalMadoka** [comment]
看一下你的代理配置，主要看一下格式。隐私信息注意打码

**Comment by MagicalMadoka** [comment]
我的意思是贴一下

**Comment by duansix** [comment]
![QQ截图20240104232152](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/83032e97-3fe3-4991-9bc1-537138ef4781)
使用上面的API形式 查看日志发现 跑2个账户之后就提示ip频繁了 感觉proxy并没有起到作用
![QQ截图20240104232512](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/f5017fe4-b6e9-4917-b633-46eb2474395c)
使用图2的账密认证模式 生成的链接是不带http://的 然后 日志调用报错 如图所示
![QQ截图20240104232747](https://github.com/MagicalMadoka/openai-signup-tool/assets/75287966/6b66a476-9fdb-4cac-b5a3-f865d04a5952)
测试了一些比较知名的平台 都是如此

**Comment by duansix** [comment]
是否能够适配一下API模式 
下面是格式：
headers = {
{“Code”: 0,”Success”: true,”Msg”: “Sucessfully extracted”,”RequestIp”: “request address”,”Data”: [{“ip”:
“Request address”,”port”: 10951},{“ip”: “13.229.125.57”,”port”: 10715}]}

**Comment by MagicalMadoka** [comment]
现在用的格式就是通用的标准格式。

别的格式如果是动态代理，你本地起一个服务转换一下就好了。如果是静态的直接写个工具转一下就好了。

**Comment by duansix** [comment]
是动态代理 不懂如何转换... 大佬可以指导一下嘛
